export const navigation = [
  {
    label: 'Overview',
    items: [
      { href: '/', label: 'Introduction' },
      { href: '/getting-started/', label: 'Getting started' },
      { href: '/typography/', label: 'Typography' },
      { href: '/theming/', label: 'Theming' },
      { href: '/motion/', label: 'Motion' },
      { href: '/composition/', label: 'Composition' },
      { href: '/integrations/', label: 'Integrations' },
    ],
  },
  {
    label: 'Product demo',
    items: [{ href: '/demo/', label: 'Field Notes' }],
  },
  {
    label: 'Components',
    items: [
      { href: '/components/', label: 'All components' },
      { href: '/components/accordion/', label: 'Accordion' },
      { href: '/components/alert/', label: 'Alert' },
      { href: '/components/avatar/', label: 'Avatar' },
      { href: '/components/badge/', label: 'Badge' },
      { href: '/components/blockquote/', label: 'Blockquote' },
      { href: '/components/bookmark/', label: 'Bookmark' },
      { href: '/components/breadcrumb/', label: 'Breadcrumb' },
      { href: '/components/button/', label: 'Button' },
      { href: '/components/callout/', label: 'Callout' },
      { href: '/components/card/', label: 'Card' },
      { href: '/components/chart/', label: 'Chart' },
      { href: '/components/checkbox/', label: 'Checkbox' },
      { href: '/components/checklist/', label: 'Checklist' },
      { href: '/components/code-block/', label: 'Code block' },
      { href: '/components/divider/', label: 'Divider' },
      { href: '/components/drawer/', label: 'Drawer' },
      { href: '/components/doodle-avatar/', label: 'Doodle avatar' },
      { href: '/components/empty-state/', label: 'Empty state' },
      { href: '/components/footer/', label: 'Footer' },
      { href: '/components/header/', label: 'Header' },
      { href: '/components/highlight/', label: 'Highlight' },
      { href: '/components/icon/', label: 'Icon' },
      { href: '/components/input/', label: 'Input' },
      { href: '/components/kanban/', label: 'Kanban' },
      { href: '/components/link/', label: 'Link' },
      { href: '/components/list/', label: 'List' },
      { href: '/components/modal/', label: 'Modal' },
      { href: '/components/note/', label: 'Note' },
      { href: '/components/pagination/', label: 'Pagination' },
      { href: '/components/popover/', label: 'Popover' },
      { href: '/components/progress/', label: 'Progress' },
      { href: '/components/radio/', label: 'Radio' },
      { href: '/components/skeleton/', label: 'Skeleton' },
      { href: '/components/slider/', label: 'Slider' },
      { href: '/components/spinner/', label: 'Spinner' },
      { href: '/components/steps/', label: 'Steps' },
      { href: '/components/sticker/', label: 'Sticker' },
      { href: '/components/switch/', label: 'Switch' },
      { href: '/components/tabs/', label: 'Tabs' },
      { href: '/components/table/', label: 'Table' },
      { href: '/components/table-of-contents/', label: 'Table of contents' },
      { href: '/components/textarea/', label: 'Textarea' },
      { href: '/components/toast/', label: 'Toast' },
      { href: '/components/tooltip/', label: 'Tooltip' },
    ],
  },
] as const
