export const navigation = [
  {
    label: 'Overview',
    items: [
      { href: '/', label: 'Introduction' },
      { href: '/getting-started/', label: 'Getting started' },
      { href: '/theming/', label: 'Theming' },
      { href: '/integrations/', label: 'Integrations' },
    ],
  },
  {
    label: 'Components',
    items: [
      { href: '/components/', label: 'All components' },
      { href: '/components/accordion/', label: 'Accordion' },
      { href: '/components/alert/', label: 'Alert' },
      { href: '/components/avatar/', label: 'Avatar' },
      { href: '/components/badge/', label: 'Badge' },
      { href: '/components/bookmark/', label: 'Bookmark' },
      { href: '/components/breadcrumb/', label: 'Breadcrumb' },
      { href: '/components/button/', label: 'Button' },
      { href: '/components/callout/', label: 'Callout' },
      { href: '/components/card/', label: 'Card' },
      { href: '/components/chart/', label: 'Chart' },
      { href: '/components/checkbox/', label: 'Checkbox' },
      { href: '/components/divider/', label: 'Divider' },
      { href: '/components/highlight/', label: 'Highlight' },
      { href: '/components/icon/', label: 'Icon' },
      { href: '/components/input/', label: 'Input' },
      { href: '/components/link/', label: 'Link' },
      { href: '/components/modal/', label: 'Modal' },
      { href: '/components/note/', label: 'Note' },
      { href: '/components/pagination/', label: 'Pagination' },
      { href: '/components/progress/', label: 'Progress' },
      { href: '/components/radio/', label: 'Radio' },
      { href: '/components/spinner/', label: 'Spinner' },
      { href: '/components/sticker/', label: 'Sticker' },
      { href: '/components/tabs/', label: 'Tabs' },
      { href: '/components/tape/', label: 'Tape' },
      { href: '/components/textarea/', label: 'Textarea' },
      { href: '/components/toast/', label: 'Toast' },
      { href: '/components/tooltip/', label: 'Tooltip' },
    ],
  },
] as const
